import type { TTFObject } from '../types'

export function getEmptyTTFObject(): TTFObject {
  const now = new Date()
  return {
    version: 0x10000,
    numTables: 0,
    searchRange: 0,
    entrySelector: 0,
    rangeShift: 0,
    head: {
      version: 1,
      fontRevision: 1,
      checkSumAdjustment: 0,
      magickNumber: 0x5F0F3CF5,
      flags: 0x0B,
      unitsPerEm: 1024,
      created: now,
      modified: now,
      xMin: 0,
      yMin: -200,
      xMax: 1024,
      yMax: 824,
      macStyle: 0,
      lowestRecPPEM: 8,
      fontDirectionHint: 2,
      indexToLocFormat: 0,
      glyphDataFormat: 0,
    },
    glyf: [
      {
        contours: [
          [
            { x: 34, y: 0, onCurve: true },
            { x: 306, y: 0, onCurve: true },
            { x: 306, y: 682, onCurve: true },
            { x: 34, y: 682, onCurve: true },
          ],
          [
            { x: 74, y: 42, onCurve: true },
            { x: 74, y: 642, onCurve: true },
            { x: 266, y: 642, onCurve: true },
            { x: 266, y: 42, onCurve: true },
          ],
        ],
        xMin: 34,
        yMin: 0,
        xMax: 306,
        yMax: 682,
        advanceWidth: 374,
        leftSideBearing: 34,
        name: '.notdef',
      },
    ],
    cmap: {},
    name: {
      fontFamily: 'Untitled',
      fontSubFamily: 'Regular',
      uniqueSubFamily: 'Untitled-Regular-1.0',
      fullName: 'Untitled',
      version: 'Version 1.0',
      postScriptName: 'Untitled-Regular',
    },
    hhea: {
      version: 1,
      ascent: 824,
      descent: -200,
      lineGap: 0,
      advanceWidthMax: 1024,
      minLeftSideBearing: 0,
      minRightSideBearing: 0,
      xMaxExtent: 0,
      caretSlopeRise: 1,
      caretSlopeRun: 0,
      caretOffset: 0,
      reserved0: 0,
      reserved1: 0,
      reserved2: 0,
      reserved3: 0,
      metricDataFormat: 0,
      numOfLongHorMetrics: 1,
    },
    post: {
      format: 3,
      italicAngle: 0,
      underlinePosition: -100,
      underlineThickness: 50,
      isFixedPitch: 0,
      minMemType42: 0,
      maxMemType42: 0,
      minMemType1: 0,
      maxMemType1: 0,
    },
    maxp: {
      version: 1,
      numGlyphs: 1,
      maxPoints: 8,
      maxContours: 2,
      maxCompositePoints: 0,
      maxCompositeContours: 0,
      maxZones: 2,
      maxTwilightPoints: 0,
      maxStorage: 0,
      maxFunctionDefs: 0,
      maxInstructionDefs: 0,
      maxStackElements: 0,
      maxSizeOfInstructions: 0,
      maxComponentElements: 0,
      maxComponentDepth: 0,
    },
    'OS/2': {
      version: 3,
      xAvgCharWidth: 374,
      usWeightClass: 400,
      usWidthClass: 5,
      fsType: 0,
      ySubscriptXSize: 640,
      ySubscriptYSize: 700,
      ySubscriptXOffset: 0,
      ySubscriptYOffset: 140,
      ySuperscriptXSize: 640,
      ySuperscriptYSize: 700,
      ySuperscriptXOffset: 0,
      ySuperscriptYOffset: 480,
      yStrikeoutSize: 50,
      yStrikeoutPosition: 260,
      sFamilyClass: 0,
      bFamilyType: 0,
      bSerifStyle: 0,
      bWeight: 0,
      bProportion: 0,
      bContrast: 0,
      bStrokeVariation: 0,
      bArmStyle: 0,
      bLetterform: 0,
      bMidline: 0,
      bXHeight: 0,
      ulUnicodeRange1: 0,
      ulUnicodeRange2: 0,
      ulUnicodeRange3: 0,
      ulUnicodeRange4: 0,
      achVendID: '----',
      fsSelection: 0x40,
      usFirstCharIndex: 0,
      usLastCharIndex: 0,
      sTypoAscender: 824,
      sTypoDescender: -200,
      sTypoLineGap: 0,
      usWinAscent: 824,
      usWinDescent: 200,
      ulCodePageRange1: 0,
      ulCodePageRange2: 0,
      sxHeight: 500,
      sCapHeight: 700,
      usDefaultChar: 0,
      usBreakChar: 32,
      usMaxContext: 0,
    },
  }
}
